version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
      - ./storage:/var/www/storage
    networks:
      - app-network
    ports:
      - "9000:9000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=project_management
      - DB_USERNAME=root
      - DB_PASSWORD=root

  db:
    image: mysql:5.7
    platform: linux/amd64  # Ensure platform is set if needed
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_management
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
